name: MSYS2

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: clang64
        location: c:\msys64_CI
        path-type: inherit
        release: false
        update: false
        cache: false

        install: >-
          git
          bash

        pacboy: >-
          git-lfs:p
          cmake:p
          clang:p
          ninja:p
          openmp:p
          libunwind:p

    - uses: actions/checkout@v4
      with:
        lfs: true
        submodules:  true
        fetch-depth:  0

    - name: cmake [configure]
      shell: msys2 {0}
      run: cmake -B build_SYS_${{env.BUILD_TYPE}}  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
